# Langfuse wrapper chart values

# Global annotations added to HTTPRoute resources
global:
  annotations:
    ark.mckinsey.com/service: langfuse

# Gateway configuration for HTTPRoute
gateway:
  # Namespace where localhost-gateway is installed
  namespace: ark-system
  # Gateway name to reference
  name: localhost-gateway

# Service configuration for HTTPRoute
service:
  name: langfuse-web
  port: 3000

# Namespace configuration
namespace: telemetry

# Demo configuration
demo:
  user:
    username: "ark@ark.com"
    password: "password123"
  admin:
    username: "admin" 
    password: "changeme123"
  project:
    publicKey: "lf_pk_1234567890"
    secretKey: "lf_sk_1234567890"

# Langfuse helm chart values (passed to dependency)
langfuse:
  langfuse:
    nextauth:
      secret: 
        value: "langfuse-nextauth-secret-change-me"
    
    salt: 
      value: "langfuse-salt-local-development-mode"
    
    encryptionKey:
      value: "cdd693af5b1ced98097c45550ea34f374fdd8d3427aa2a6a96a2204017a8caf3"

    # Demo initialization environment variables
    additionalEnv:
      - name: LANGFUSE_INIT_ORG_ID
        value: "ark"
      - name: LANGFUSE_INIT_ORG_NAME
        value: "Ark"
      - name: LANGFUSE_INIT_PROJECT_ID
        value: "ark"
      - name: LANGFUSE_INIT_PROJECT_NAME
        value: "Ark"
      - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
        value: "lf_pk_1234567890"
      - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
        value: "lf_sk_1234567890"
      - name: LANGFUSE_INIT_USER_EMAIL
        value: "ark@ark.com"
      - name: LANGFUSE_INIT_USER_NAME
        value: "Ark Administrators"
      - name: LANGFUSE_INIT_USER_PASSWORD
        value: "password123"
      # S3/MinIO configuration
      - name: AWS_ACCESS_KEY_ID
        value: "admin"
      - name: AWS_SECRET_ACCESS_KEY
        value: "password"
      - name: AWS_ENDPOINT_URL_S3
        value: "http://langfuse-s3:9000"
      - name: AWS_REGION
        value: "us-east-1"
    
  postgresql:
    enabled: true
    auth:
      password: "changeme123"
      database: "langfuse"
    
  clickhouse:
    enabled: true
    shards: 1
    replicaCount: 1
    auth:
      password: "clickhouse123"
      
  redis:
    enabled: true
    auth:
      password: "redis123"
  
  s3:
    enabled: true
    auth:
      rootUser: "admin"
      rootPassword: "password"