# ARK API A2A chart values

# Application configuration
app:
  image:
    repository: ghcr.io/mckinsey/agents-at-scale-ark/ark-api-a2a
    tag: "{{ .Chart.AppVersion | default .Chart.Version }}"
    pullPolicy: IfNotPresent

# Global annotations added to HTTPRoute resources
global:
  annotations:
    ark.mckinsey.com/service: ark-api-a2a

# Gateway configuration for HTTPRoute
gateway:
  # Namespace where localhost-gateway is installed
  namespace: ark-system
  # Gateway name to reference
  name: localhost-gateway

# Service configuration for HTTPRoute
service:
  name: ark-api-a2a
  port: 80

# Service account configuration
serviceAccount:
  name: ark-api-a2a-sa
  create: true

# Namespace configuration
namespace: default

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi