apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ark
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: ark-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: ark-controller
    app.kubernetes.io/name: ark
