name: 'Setup E2E Environment'
description: 'Sets up E2E test environment with K8s cluster, tools, and ARK deployment'

inputs:
  ci-cache-registry:
    description: 'CI cache container registry URL'
    required: false
    default: ''
  ci-cache-registry-username:
    description: 'CI cache registry username'
    required: false
    default: ''
  ci-cache-registry-password:
    description: 'CI cache registry password'
    required: false
    default: ''
  ark-image-tag:
    description: 'ARK image tag to deploy'
    required: false
    default: 'latest'
  azure-openai-key:
    description: 'Azure OpenAI API key for default model'
    required: false
    default: ''
  azure-openai-base-url:
    description: 'Azure OpenAI base URL for default model'
    required: false
    default: ''
  install-coverage:
    description: 'Install coverage collection components'
    required: false
    default: 'false'
  install-evaluator:
    description: 'Install ark-evaluator service for evaluation tests'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Configure K3s registry authentication
      shell: bash
      run: |
        sudo mkdir -p /etc/rancher/k3s
        # Use provided registry or default to ghcr.io/{repository_owner}
        REGISTRY="${{ inputs.ci-cache-registry || format('ghcr.io/{0}', github.repository_owner) }}"
        USERNAME="${{ inputs.ci-cache-registry-username || github.actor }}"
        PASSWORD="${{ inputs.ci-cache-registry-password || github.token }}"
        
        # Extract registry hostname (e.g., ghcr.io from ghcr.io/org)
        REGISTRY_HOST=$(echo "$REGISTRY" | cut -d'/' -f1)
        
        echo "Configuring K3s registry authentication for: $REGISTRY_HOST"
        
        cat <<EOF | sudo tee /etc/rancher/k3s/registries.yaml
        mirrors:
          $REGISTRY_HOST:
            endpoint:
              - "https://$REGISTRY_HOST"
        configs:
          $REGISTRY_HOST:
            auth:
              username: $USERNAME
              password: $PASSWORD
        EOF

    - name: Setup K3s cluster
      uses: ./.github/actions/setup-k3s
      with:
        metrics-enabled: false
        traefik-enabled: false
        k3s-channel: latest

    - name: Run setup-e2e script
      shell: bash
      run: |
        ./.github/actions/setup-e2e/setup-local.sh \
          ${{ inputs.install-coverage == 'true' && '--install-coverage' || '' }} \
          ${{ inputs.install-evaluator == 'true' && '--install-evaluator' || '' }}
      env:
        DOCKER_CICD_CACHE_REGISTRY: ${{ inputs.ci-cache-registry || format('ghcr.io/{0}', github.repository_owner) }}
        DOCKER_CICD_CACHE_REGISTRY_USERNAME: ${{ inputs.ci-cache-registry-username || github.actor }}
        DOCKER_CICD_CACHE_REGISTRY_PASSWORD: ${{ inputs.ci-cache-registry-password || github.token }}
        ARK_IMAGE_TAG: ${{ inputs.ark-image-tag }}
        AZURE_OPENAI_KEY: ${{ inputs.azure-openai-key }}
        AZURE_OPENAI_BASE_URL: ${{ inputs.azure-openai-base-url }}
